_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
algorithm:
    value: PPO
batch_size:
    value: 128
clip_range:
    value: 0.2
ent_coef:
    value: 0.05
gamma:
    value: 0.99
learning_rate:
    value: 0.0005
n_steps:
    value: 1024
tensorboard_log:
    value: ./tb
