_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[ 1.24629003e+00 -1.53949256e-03  4.16316533e-03  1.73832510e-03
           3.02346361e-03 -4.39627533e-03  6.77507337e-04 -3.23675869e-03
           1.16287932e-03 -3.59290438e-03 -4.11137018e-03]
         [ 1.24549020e+00 -3.51935558e-03 -5.48940590e-05 -1.09723850e-03
          -8.28422376e-04 -2.32726870e-03  1.85922214e-03  3.08859254e-03
           1.95108761e-03  1.08649720e-03  4.05423201e-03]
         [ 1.24510293e+00 -2.65018413e-04  1.79315916e-03 -3.98902072e-03
           1.52374110e-03 -4.14793216e-03 -4.07539510e-03  4.30097861e-03
           4.45564988e-04  4.21067535e-03  2.35931368e-03]
         [ 1.24673233e+00  1.96461866e-03 -3.54051717e-03 -1.94263900e-03
          -3.15396744e-03  4.58147613e-03  4.77690012e-05  2.29718540e-03
           2.99131056e-03 -4.98659767e-03 -4.13055725e-03]
         [ 1.24701291e+00  9.88565498e-04 -3.65413977e-03  4.01793038e-04
           1.29152918e-03  1.05399858e-03  3.62596261e-03  1.18757461e-03
           4.41613754e-03 -1.08719473e-03 -5.50009522e-04]
         [ 1.24532949e+00 -3.19815146e-03  2.86948073e-03 -3.30110322e-03
          -1.62038251e-03 -3.31958373e-03  3.87191242e-03  9.56355702e-04
          -1.72501419e-03 -4.97946094e-03 -3.29594174e-03]
         [ 1.24829394e+00  6.67159968e-04 -7.68262161e-04  3.45797994e-03
           2.25997198e-03 -2.14423425e-03 -3.66301500e-03 -2.28804136e-03
           1.28752684e-03  3.79160884e-04  2.82376993e-03]
         [ 1.24859515e+00  8.07878027e-04  3.40614934e-03  4.09603544e-03
          -3.99223186e-03  3.73963490e-03  1.45869054e-03 -1.84382773e-03
          -7.75384636e-04 -9.51878430e-04  2.87811305e-03]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x1387c0a50>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 1000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 3
                - 13
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (3,), float32)
algo:
    value: PPO
algorithm:
    value: PPO
batch_size:
    value: 128
clip_range:
    value: 0.2
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0.05
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x12ff3e150>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0005
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x10485d580>
max_grad_norm:
    value: 0.5
n_envs:
    value: 8
n_epochs:
    value: 10
n_steps:
    value: 1024
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (11,), float64)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=11, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=11, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=3, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x138730a10>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1747771010471547000
target_kl:
    value: None
tensorboard_log:
    value: ./tb
use_sde:
    value: "False"
verbose:
    value: 0
vf_coef:
    value: 0.5
