_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[ 1.24986013e+00  4.27697942e-03  2.07966648e-03  1.28882953e-03
          -1.25673446e-03 -2.57925858e-04  3.82498611e-04 -3.27409166e-03
           2.73158116e-03  2.24849845e-03 -4.07496082e-04]
         [ 1.24518879e+00  2.38139208e-03  7.67316579e-04  2.89965372e-03
           4.46595732e-03  4.93150093e-03 -4.67805011e-03 -4.87265736e-03
           4.88519884e-04  2.81499591e-03  3.28953901e-04]
         [ 1.24958583e+00 -2.04659413e-03 -3.05335959e-03  3.27303951e-03
          -2.08990443e-04 -1.46857782e-03 -3.10928194e-03  1.64829611e-03
          -1.82940348e-03 -4.86274624e-03 -4.43642202e-03]
         [ 1.25237673e+00  3.90106349e-03 -3.24363746e-03  2.50011224e-04
           3.86321175e-03  6.04370334e-05  2.74841205e-03 -1.45563584e-03
           3.48573865e-03  4.93438872e-03 -2.75568433e-03]
         [ 1.24551935e+00 -4.01925755e-03 -1.28641542e-03  1.96242050e-03
          -9.72295521e-05  3.15940503e-03 -1.60633734e-03 -4.02527419e-03
           4.73074842e-03  3.07107476e-04 -1.56892254e-03]
         [ 1.24930095e+00  4.65955060e-03  2.60082441e-03 -1.11639483e-03
          -1.31141793e-03  7.71975166e-04 -6.38870475e-04 -8.70486156e-04
           5.46324209e-04  1.48441550e-03  4.63901747e-03]
         [ 1.25348726e+00  2.35420223e-04  1.01090504e-03  4.05936915e-04
          -3.45721105e-03 -4.27168415e-03  2.77457611e-03  3.88949073e-03
          -3.81482807e-03  3.66282742e-03 -5.53426061e-06]
         [ 1.25454085e+00 -3.75193389e-03 -2.77921572e-03  2.37188463e-03
           4.04907468e-04  3.33087858e-03 -4.97497438e-03 -2.98212741e-03
          -2.67445352e-03 -4.77006625e-03 -5.12205170e-04]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x3140701d0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 1000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 3
                - 13
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (3,), float32)
algo:
    value: PPO
algorithm:
    value: PPO
batch_size:
    value: 128
clip_range:
    value: 0.2
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0.05
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x14528de10>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0005
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x110eb1580>
max_grad_norm:
    value: 0.5
n_envs:
    value: 8
n_epochs:
    value: 10
n_steps:
    value: 1024
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (11,), float64)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=11, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=11, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=3, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x145257b50>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1747769429542810000
target_kl:
    value: None
tensorboard_log:
    value: ./tb
use_sde:
    value: "False"
verbose:
    value: 0
vf_coef:
    value: 0.5
